# Generated by Django 3.0.3 on 2020-02-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, 'ruuvi'), (1, 'qicka_sensor'), (2, 'qicka_clock')])),
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nodes', models.ManyToManyField(blank=True, to='data_logger.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('resolution', models.IntegerField(choices=[(0, 'real_time'), (10, 'hour'), (20, 'day')], default=0)),
                ('type', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger.Node')),
            ],
        ),
    ]
