# Generated by Django 3.0.3 on 2020-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0003_auto_20200223_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='settings',
            field=models.ManyToManyField(blank=True, to='data_logger.NodeSettings'),
        ),
    ]
