# Generated by Django 3.0.3 on 2020-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0005_auto_20200225_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='setting',
            field=models.IntegerField(choices=[(10, 'TEMP_FORWARD'), (11, 'RANDOM_SETTING')]),
        ),
    ]
