# Generated by Django 3.0.3 on 2020-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0007_auto_20200225_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.CharField(max_length=512),
        ),
    ]
