# Generated by Django 3.0.3 on 2020-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0011_auto_20201127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.IntegerField(choices=[(0, 'ruuvi'), (1, 'qicka_sensor'), (2, 'qicka_clock'), (3, 'qicka_sleep_traffic_light')]),
        ),
        migrations.AlterField(
            model_name='nodesettings',
            name='setting',
            field=models.IntegerField(choices=[(10, 'TEMP_FORWARD'), (11, 'RANDOM_SETTING'), (12, 'ALERT_TIME')]),
        ),
    ]
