# Generated by Django 3.1.4 on 2021-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0012_auto_20201228_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='resolution',
            field=models.IntegerField(choices=[(0, 'real_time'), (10, 'hour_avg'), (20, '12_hour_avg'), (30, '24_hour_avg')], default=0),
        ),
    ]
