# Generated by Django 3.0.3 on 2020-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='update_interval_seconds',
            field=models.IntegerField(choices=[(30, '30 seconds'), (60, 'minute'), (90, 'minute and a half'), (120, 'two minutes'), (150, 'two and a half minutes'), (180, 'three minutes'), (210, 'three and a half minutes')], default=120),
        ),
    ]
