# Generated by Django 3.0.3 on 2020-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger_api', '0002_gateway_update_interval_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='resolution',
            field=models.IntegerField(choices=[(0, 'real_time'), (10, 'hour_avg'), (20, 'day_avg')], default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='settings',
            field=models.ManyToManyField(blank=True, null=True, to='data_logger_api.NodeSettings'),
        ),
    ]
