# Generated by Django 3.0.3 on 2020-02-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger_api', '0006_auto_20200225_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(10, 'is less than'), (20, 'is less or equal to'), (30, 'is more than'), (40, 'is more or equal to'), (50, 'is equal to')])),
                ('field', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nodesettings',
            options={'verbose_name_plural': 'Node settings'},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_logger_api.Node')),
                ('rules', models.ManyToManyField(to='data_logger_api.AlertRule')),
            ],
        ),
    ]
