# Generated by Django 3.0.3 on 2020-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger_api', '0009_auto_20200710_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
