# Generated by Django 3.0.3 on 2020-11-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger_api', '0010_auto_20201127_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='nodes',
        ),
        migrations.AddField(
            model_name='node',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_logger_api.Gateway'),
        ),
    ]
