name: Vuohiportal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo mkdir -p /CloudFS/vuohiportal/configs/
        sudo chmod 777 /CloudFS/vuohiportal/configs/ -R
        cp settings.ini.example /CloudFS/vuohiportal/configs/settings.ini
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-18.04
    needs: [build]
    name: Deploy to production
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: scp deployment
      uses: horochx/deploy-via-scp@v1.0.1
      with:
        local: ./* # eg: dist
        remote: ${{ secrets.TARGET }} # eg: /home/github-action
        host: ${{ secrets.HOST }} # eg: example.com
        port: ${{ secrets.PORT }} # eg: 22
        user: ${{ secrets.USERNAME }} # eg: github-action
        key: ${{ secrets.KEY }} # eg: -----BEGIN OPENSSH PRIVATE KEY-----\nHEIiyzh5cT7hN...

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.TARGET }}
          bash post_deploy.sh