# Generated by Django 3.1.4 on 2021-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPublicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profession', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.TextField()),
                ('title', models.TextField()),
                ('branch', models.TextField(blank=True, null=True)),
                ('graduation_date', models.DateTimeField()),
                ('rating_scale', models.TextField(blank=True, null=True)),
                ('average_rating', models.TextField(blank=True, null=True)),
                ('thesis', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('profession', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'FUNDAMENTAL_AWARNESS'), (5, 'EXPERT'), (3, 'INTERMEDIATE'), (2, 'NOVICE'), (4, 'ADVANCED')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='OtherInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'FUNDAMENTAL_AWARNESS'), (5, 'EXPERT'), (3, 'INTERMEDIATE'), (2, 'NOVICE'), (4, 'ADVANCED')], max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(choices=[('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('INSTA', 'Instagram'), ('FACE', 'Facebook')])),
                ('url', models.URLField()),
                ('name', models.TextField()),
            ],
        ),
    ]
