# Generated by Django 3.1.4 on 2021-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpublicinfo',
            name='location',
            field=models.TextField(default='Turku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languageskills',
            name='level',
            field=models.IntegerField(choices=[(1, 'FUNDAMENTAL_AWARNESS'), (2, 'NOVICE'), (4, 'ADVANCED'), (5, 'EXPERT'), (3, 'INTERMEDIATE')], max_length=24),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='level',
            field=models.IntegerField(choices=[(1, 'FUNDAMENTAL_AWARNESS'), (2, 'NOVICE'), (4, 'ADVANCED'), (5, 'EXPERT'), (3, 'INTERMEDIATE')], max_length=24),
        ),
        migrations.AlterField(
            model_name='socials',
            name='service',
            field=models.TextField(choices=[('FACE', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('INSTA', 'Instagram')]),
        ),
    ]
