# Generated by Django 3.1.4 on 2021-03-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210305_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='languageskills',
            name='level',
            field=models.IntegerField(choices=[(3, 'INTERMEDIATE'), (1, 'FUNDAMENTAL_AWARNESS'), (2, 'NOVICE'), (5, 'EXPERT'), (4, 'ADVANCED')]),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='level',
            field=models.IntegerField(choices=[(3, 'INTERMEDIATE'), (1, 'FUNDAMENTAL_AWARNESS'), (2, 'NOVICE'), (5, 'EXPERT'), (4, 'ADVANCED')]),
        ),
        migrations.AlterField(
            model_name='socials',
            name='service',
            field=models.TextField(choices=[('INSTA', 'Instagram'), ('GITHUB', 'GitHub'), ('LINKEDIN', 'LinkedIn'), ('FACE', 'Facebook')]),
        ),
    ]
