# Generated by Django 3.1.4 on 2021-03-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20210308_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpublicinfo',
            name='language',
            field=models.CharField(choices=[('fi', 'Suomi'), ('en', 'English')], default='fi', max_length=2),
        ),
        migrations.AlterField(
            model_name='education',
            name='language',
            field=models.CharField(choices=[('fi', 'Suomi'), ('en', 'English')], default='fi', max_length=2),
        ),
        migrations.AlterField(
            model_name='experience',
            name='language',
            field=models.CharField(choices=[('fi', 'Suomi'), ('en', 'English')], default='fi', max_length=2),
        ),
        migrations.AlterField(
            model_name='languageskills',
            name='level',
            field=models.IntegerField(choices=[(2, 'NOVICE'), (1, 'FUNDAMENTAL_AWARNESS'), (4, 'ADVANCED'), (5, 'EXPERT'), (3, 'INTERMEDIATE')]),
        ),
        migrations.AlterField(
            model_name='otherinterests',
            name='language',
            field=models.CharField(choices=[('fi', 'Suomi'), ('en', 'English')], default='fi', max_length=2),
        ),
        migrations.AlterField(
            model_name='professionalskills',
            name='level',
            field=models.IntegerField(choices=[(2, 'NOVICE'), (1, 'FUNDAMENTAL_AWARNESS'), (4, 'ADVANCED'), (5, 'EXPERT'), (3, 'INTERMEDIATE')]),
        ),
        migrations.AlterField(
            model_name='socials',
            name='language',
            field=models.CharField(choices=[('fi', 'Suomi'), ('en', 'English')], default='fi', max_length=2),
        ),
        migrations.AlterField(
            model_name='socials',
            name='service',
            field=models.TextField(choices=[('INSTA', 'Instagram'), ('FACE', 'Facebook'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub')]),
        ),
    ]
